<a href="https://colab.research.google.com/github/syamjithz/ML-Self-Study/blob/main/Multiple_Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1. Sample**

In [ ]:
import pandas as pd
import math

In [ ]:
from sklearn import linear_model

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/Datasets_for_AIML/ML/houseprices_many.csv")
df

area  bedrooms  age    price
0  2600       3.0   20  5500000
1  3000       4.0   15  5650000
2  3200       NaN   18  6100000
3  3300       3.0   30  5950000
4  4000       5.0    8  7600000

In [ ]:
# checking is there any null values present in the dataset
df.isnull().sum()

area        0
bedrooms    1
age         0
price       0
dtype: int64

In [ ]:
med = math.floor(df.bedrooms.median()) # floor() will round down a floating-point number to the nearest integer value that is less than or equal to the original number
df.bedrooms = df.bedrooms.fillna(med)
df

area  bedrooms  age    price
0  2600       3.0   20  5500000
1  3000       4.0   15  5650000
2  3200       3.0   18  6100000
3  3300       3.0   30  5950000
4  4000       5.0    8  7600000

In [ ]:
from sklearn import linear_model
reg = linear_model.LinearRegression()
reg.fit(df[["area","bedrooms","age"]],df.price)

LinearRegression()

In [ ]:
reg.coef_

array([   1483.78378378, -137837.83783784,  -34864.86486486])

In [ ]:
reg.intercept_

2512972.9729729705

In [ ]:
reg.predict([[3000,3,40]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([5156216.21621621])

**2. Profit Calculation**

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = pd.read_csv("/content/drive/MyDrive/Datasets_for_AIML/ML/1000_Companies.csv")
data.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [ ]:
data.isnull().sum()

R&D Spend          0
Administration     0
Marketing Spend    0
State              0
Profit             0
dtype: int64

In [ ]:
# splitting dependant and independant variables

X = data.iloc[:,0:4]      # or [:,0:-1]
y = data.iloc[:,-1]

In [ ]:
X

R&D Spend  Administration  Marketing Spend       State
0    165349.20      136897.800      471784.1000    New York
1    162597.70      151377.590      443898.5300  California
2    153441.51      101145.550      407934.5400     Florida
3    144372.41      118671.850      383199.6200    New York
4    142107.34       91391.770      366168.4200     Florida
..         ...             ...              ...         ...
995   54135.00      118451.999      173232.6695  California
996  134970.00      130390.080      329204.0228  California
997  100275.47      241926.310      227142.8200  California
998  128456.23      321652.140      281692.3200  California
999  161181.72      270939.860      295442.1700    New York

[1000 rows x 4 columns]

In [ ]:
y

0      192261.83000
1      191792.06000
2      191050.39000
3      182901.99000
4      166187.94000
           ...     
995     95279.96251
996    164336.60550
997    413956.48000
998    333962.19000
999    476485.43000
Name: Profit, Length: 1000, dtype: float64

In [ ]:
# Applying one hot encoding
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer  #just tell which column has to be converted in to onehot encoder
ct = ColumnTransformer([("Country",OneHotEncoder(),[3])],remainder = "passthrough")
X = ct.fit_transform(X)

ct = ColumnTransformer ( [ ( " Any random name " , object of which encoder want to use , for which column index ) ] ,remainder = " passthrough means do not change anything that remaining " )


In [ ]:
X

array([[0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.6534920e+05,
        1.3689780e+05, 4.7178410e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.6259770e+05,
        1.5137759e+05, 4.4389853e+05],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.5344151e+05,
        1.0114555e+05, 4.0793454e+05],
       ...,
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.0027547e+05,
        2.4192631e+05, 2.2714282e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.2845623e+05,
        3.2165214e+05, 2.8169232e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.6118172e+05,
        2.7093986e+05, 2.9544217e+05]])

whenever dummy variable is assigned, we need to drop one column otherwise it will end up in multicollinerality

In [ ]:
X = X[:,1:] # first column droped or not considered
X

array([[0.0000000e+00, 1.0000000e+00, 1.6534920e+05, 1.3689780e+05,
        4.7178410e+05],
       [0.0000000e+00, 0.0000000e+00, 1.6259770e+05, 1.5137759e+05,
        4.4389853e+05],
       [1.0000000e+00, 0.0000000e+00, 1.5344151e+05, 1.0114555e+05,
        4.0793454e+05],
       ...,
       [0.0000000e+00, 0.0000000e+00, 1.0027547e+05, 2.4192631e+05,
        2.2714282e+05],
       [0.0000000e+00, 0.0000000e+00, 1.2845623e+05, 3.2165214e+05,
        2.8169232e+05],
       [0.0000000e+00, 1.0000000e+00, 1.6118172e+05, 2.7093986e+05,
        2.9544217e+05]])

test train split

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

Creating regression model

In [ ]:
from sklearn.linear_model import LinearRegression
reg = linear_model.LinearRegression()
reg.fit(X_train,y_train)

LinearRegression()

prediction

In [ ]:
y_pred = reg.predict(X_test)
y_pred

array([ 89790.61532915,  88427.07187361,  94894.67836971, 175680.86725611,
        83411.73042088, 110571.90200074, 132145.2293644 ,  91473.37719686,
       164597.05380607,  53222.826674  ,  66950.19050989, 150566.43987005,
       126915.20858596,  59337.85971049, 177513.91053062,  75316.2814305 ,
       118248.14406603, 164574.40699902, 170937.2898107 , 182069.11645085,
       118845.03252689,  85669.95112228, 180992.59396144,  84145.08220144,
       105005.83769214, 101233.56772746,  53831.0766909 ,  56881.41475223,
        68896.39346904, 210040.00765885, 120778.72270894, 111724.87157654,
       101487.90541517, 137959.02649624,  63969.95996742, 108857.91214126,
       186014.72531989, 171442.64130748, 174644.26529205, 117671.49128195,
        96731.37857433, 165452.2577941 , 107724.34331255,  50194.54176912,
       116513.89532179,  58632.4898682 , 158416.4682761 ,  78541.48521609,
       159727.66671744, 131137.87699644, 184880.70924517, 174609.08266881,
        93745.66352058,  

In [ ]:
X_test.shape

(200, 5)

In [ ]:
y_pred.shape

(200,)

For column "state" value is changed to like 0,0,1 because it undergone onehoit encoding and from this one column is droped too there for only 2 column is remaining and the remaining column is added to the first

In [ ]:
a = reg.predict([[0,1,195349,165897.8,741784.10]])
a

array([270869.5253266])

In [ ]:
b = reg.predict([[1,0,205349,305897.8,331784.10]])
b

array([350054.89498484])

In [ ]:
data.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94